# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks


# Autopep8 hook : runs for python files
repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    -   id: autopep8


# Pylint hook : runs for python files
-   repo: https://github.com/pycqa/pylint
    rev: v2.10.2
    hooks:
    -   id: pylint
        args:
        - --max-line-length=120
        # - --ignore-imports=yes
        # - -d duplicate-code
