/***************************GATE_SETTLE_PER_ITEM***** ***************************** ***************************
    Include the GATEWAY SETTLE FEE TID "010004120003" to all
    the active posting plans for institution 101,105,107,121.
    Mimic "010004120003" like existing fee tid "010004130003"
****************************************************************************************************************/
INSERT INTO acct_posting_plan (
    institution_id,
    acct_pplan_id,
    tid_to_post,
    curr_code,
    card_sch_to_post,
    entity_acct_id,
    acct_posting_type,
    payment_method_cd,
    acct_accum_method,
    payment_cycle,
    inst_cnv_plan_id
)
    SELECT DISTINCT
        app.institution_id,
        app.acct_pplan_id,
        '010004120003' tid_to_post,
        app.curr_code,
        app.card_sch_to_post,
        app.entity_acct_id,
        app.acct_posting_type,
        app.payment_method_cd,
        app.acct_accum_method,
        app.payment_cycle,
        app.inst_cnv_plan_id
    FROM
        acct_posting_plan   app
        JOIN acq_entity ae 
        ON ae.acct_pplan_id = app.acct_pplan_id
        AND ae.institution_id = app.institution_id
    WHERE
        app.institution_id IN (101,105,107,121)
        AND app.tid_to_post = '010004130003'
        AND ae.entity_status = 'A'
        AND app.card_sch_to_post NOT IN ('07','09','12')
    MINUS
    SELECT
        *
    FROM
        acct_posting_plan
    WHERE
        tid_to_post = '010004120003'
        AND institution_id IN (101,105,107,121)
    ORDER BY
        1,2,3,4,5;

Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('101','10','010004120003','840','02',null,'F','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('101','2','010004120003','840','02',null,'O','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('101','3','010004120003','840','02',null,'F','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('101','5','010004120003','840','02',null,'F','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('101','8','010004120003','840','02',null,'F','A','D','6 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('101','6','010004120003','840','02',null,'A','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('105','2','010004120003','840','02',null,'O','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('105','3','010004120003','840','02',null,'F','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('105','5','010004120003','840','02',null,'F','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('105','7','010004120003','840','02',null,'F','A','D','7 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('105','1','010004120003','840','02',null,'A','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('105','6','010004120003','840','02',null,'A','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('107','2','010004120003','840','02',null,'O','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('107','5','010004120003','840','02',null,'F','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('107','9','010004120003','840','02',null,'F','A','D','5 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('107','10','010004120003','840','02',null,'F','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('107','110','010004120003','840','02',null,'F','T','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('107','15','010004120003','840','02',null,'A','N','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('107','16','010004120003','840','02',null,'A','A','D','5 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('107','19','010004120003','840','02',null,'A','N','D','5 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('107','3','010004120003','840','02',null,'F','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('107','6','010004120003','840','02',null,'A','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('121','9','010004120003','840','02',null,'F','A','D','5 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('121','10','010004120003','840','02',null,'F','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('121','5','010004120003','840','02',null,'F','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('121','6','010004120003','840','02',null,'A','A','D','1 ',null);
Insert into ACCT_POSTING_PLAN (INSTITUTION_ID,ACCT_PPLAN_ID,TID_TO_POST,CURR_CODE,CARD_SCH_TO_POST,ENTITY_ACCT_ID,ACCT_POSTING_TYPE,PAYMENT_METHOD_CD,ACCT_ACCUM_METHOD,PAYMENT_CYCLE,INST_CNV_PLAN_ID) values ('121','7','010004120003','840','02',null,'F','A','D','7 ',null);
COMMIT;