merge into SETTL_PLAN sp using 
(select settl_plan_id,PLAN_DESC,SETTL_PLAN_TYPE from settl_plan where 
SETTL_PLAN_ID between 111 and 147  
and INSTITUTION_ID = '130') osp 
on (sp.settl_plan_id = osp.settl_plan_id 
and (SETTL_PLAN_ID between 111 and 117   or SETTL_PLAN_ID between 121 and 127 or SETTL_PLAN_ID between 131 and 137 or SETTL_PLAN_ID between 141 and 147 )
and sp.INSTITUTION_ID = '101')
when matched then update set sp.PLAN_DESC = osp.PLAN_DESC,sp.SETTL_PLAN_TYPE = osp.SETTL_PLAN_TYPE
when not matched then insert ( INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('101',osp.SETTL_PLAN_ID,osp.PLAN_DESC,osp.SETTL_PLAN_TYPE);

REM INSERTING into SETTL_PLAN
SET DEFINE OFF;
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',111,'Pass Thru Gros Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',112,'Pass Thru Gros Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',113,'Pass Thru Gros Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',114,'Pass Thru Gros Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',115,'Pass Thru Gros Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',116,'Pass Thru Gros Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',117,'Pass Thru Gros Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',121,'Bundled Gross Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',122,'Bundled Gross Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',123,'Bundled Gross Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',124,'Bundled Gross Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',125,'Bundled Gross Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',126,'Bundled Gross Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',127,'Bundled Gross Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',131,'Pass Thru Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',132,'Pass Thru Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',133,'Pass Thru Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',134,'Pass Thru Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',135,'Pass Thru Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',136,'Pass Thru Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',137,'Pass Thru Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',141,'Bundled Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',142,'Bundled Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',143,'Bundled Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',144,'Bundled Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',145,'Bundled Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',146,'Bundled Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('105',147,'Bundled Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',111,'Pass Thru Gros Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',112,'Pass Thru Gros Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',113,'Pass Thru Gros Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',114,'Pass Thru Gros Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',115,'Pass Thru Gros Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',116,'Pass Thru Gros Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',117,'Pass Thru Gros Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',121,'Bundled Gross Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',122,'Bundled Gross Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',123,'Bundled Gross Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',124,'Bundled Gross Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',125,'Bundled Gross Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',126,'Bundled Gross Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',127,'Bundled Gross Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',131,'Pass Thru Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',132,'Pass Thru Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',133,'Pass Thru Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',134,'Pass Thru Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',135,'Pass Thru Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',136,'Pass Thru Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',137,'Pass Thru Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',141,'Bundled Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',142,'Bundled Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',143,'Bundled Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',144,'Bundled Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',145,'Bundled Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',146,'Bundled Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('107',147,'Bundled Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',111,'Pass Thru Gros Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',112,'Pass Thru Gros Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',113,'Pass Thru Gros Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',114,'Pass Thru Gros Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',115,'Pass Thru Gros Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',116,'Pass Thru Gros Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',117,'Pass Thru Gros Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',121,'Bundled Gross Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',122,'Bundled Gross Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',123,'Bundled Gross Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',124,'Bundled Gross Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',125,'Bundled Gross Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',126,'Bundled Gross Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',127,'Bundled Gross Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',131,'Pass Thru Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',132,'Pass Thru Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',133,'Pass Thru Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',134,'Pass Thru Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',135,'Pass Thru Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',136,'Pass Thru Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',137,'Pass Thru Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',141,'Bundled Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',142,'Bundled Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',143,'Bundled Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',144,'Bundled Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',145,'Bundled Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',146,'Bundled Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('121',147,'Bundled Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',111,'Pass Thru Gros Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',112,'Pass Thru Gros Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',113,'Pass Thru Gros Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',114,'Pass Thru Gros Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',115,'Pass Thru Gros Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',116,'Pass Thru Gros Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',117,'Pass Thru Gros Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',121,'Bundled Gross Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',122,'Bundled Gross Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',123,'Bundled Gross Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',124,'Bundled Gross Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',125,'Bundled Gross Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',126,'Bundled Gross Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',127,'Bundled Gross Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',131,'Pass Thru Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',132,'Pass Thru Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',133,'Pass Thru Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',134,'Pass Thru Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',135,'Pass Thru Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',136,'Pass Thru Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',137,'Pass Thru Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',141,'Bundled Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',142,'Bundled Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',143,'Bundled Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',144,'Bundled Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',145,'Bundled Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',146,'Bundled Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('129',147,'Bundled Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',111,'Pass Thru Gros Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',112,'Pass Thru Gros Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',113,'Pass Thru Gros Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',114,'Pass Thru Gros Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',115,'Pass Thru Gros Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',116,'Pass Thru Gros Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',117,'Pass Thru Gros Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',121,'Bundled Gross Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',122,'Bundled Gross Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',123,'Bundled Gross Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',124,'Bundled Gross Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',125,'Bundled Gross Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',126,'Bundled Gross Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',127,'Bundled Gross Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',131,'Pass Thru Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',132,'Pass Thru Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',133,'Pass Thru Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',134,'Pass Thru Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',135,'Pass Thru Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',136,'Pass Thru Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',137,'Pass Thru Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',141,'Bundled Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',142,'Bundled Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',143,'Bundled Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',144,'Bundled Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',145,'Bundled Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',146,'Bundled Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('130',147,'Bundled Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',111,'Pass Thru Gros Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',112,'Pass Thru Gros Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',113,'Pass Thru Gros Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',114,'Pass Thru Gros Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',115,'Pass Thru Gros Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',116,'Pass Thru Gros Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',117,'Pass Thru Gros Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',121,'Bundled Gross Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',122,'Bundled Gross Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',123,'Bundled Gross Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',124,'Bundled Gross Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',125,'Bundled Gross Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',126,'Bundled Gross Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',127,'Bundled Gross Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',131,'Pass Thru Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',132,'Pass Thru Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',133,'Pass Thru Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',134,'Pass Thru Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',135,'Pass Thru Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',136,'Pass Thru Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',137,'Pass Thru Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',141,'Bundled Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',142,'Bundled Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',143,'Bundled Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',144,'Bundled Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',145,'Bundled Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',146,'Bundled Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('131',147,'Bundled Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',111,'Pass Thru Gros Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',112,'Pass Thru Gros Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',113,'Pass Thru Gros Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',114,'Pass Thru Gros Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',115,'Pass Thru Gros Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',116,'Pass Thru Gros Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',117,'Pass Thru Gros Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',121,'Bundled Gross Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',122,'Bundled Gross Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',123,'Bundled Gross Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',124,'Bundled Gross Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',125,'Bundled Gross Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',126,'Bundled Gross Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',127,'Bundled Gross Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',131,'Pass Thru Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',132,'Pass Thru Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',133,'Pass Thru Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',134,'Pass Thru Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',135,'Pass Thru Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',136,'Pass Thru Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',137,'Pass Thru Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',141,'Bundled Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',142,'Bundled Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',143,'Bundled Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',144,'Bundled Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',145,'Bundled Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',146,'Bundled Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('132',147,'Bundled Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',111,'Pass Thru Gros Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',112,'Pass Thru Gros Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',113,'Pass Thru Gros Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',114,'Pass Thru Gros Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',115,'Pass Thru Gros Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',116,'Pass Thru Gros Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',117,'Pass Thru Gros Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',121,'Bundled Gross Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',122,'Bundled Gross Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',123,'Bundled Gross Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',124,'Bundled Gross Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',125,'Bundled Gross Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',126,'Bundled Gross Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',127,'Bundled Gross Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',131,'Pass Thru Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',132,'Pass Thru Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',133,'Pass Thru Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',134,'Pass Thru Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',135,'Pass Thru Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',136,'Pass Thru Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',137,'Pass Thru Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',141,'Bundled Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',142,'Bundled Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',143,'Bundled Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',144,'Bundled Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',145,'Bundled Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',146,'Bundled Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('133',147,'Bundled Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',111,'Pass Thru Gros Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',112,'Pass Thru Gros Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',113,'Pass Thru Gros Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',114,'Pass Thru Gros Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',115,'Pass Thru Gros Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',116,'Pass Thru Gros Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',117,'Pass Thru Gros Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',121,'Bundled Gross Monthly 1 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',122,'Bundled Gross Monthly 2 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',123,'Bundled Gross Monthly 3 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',124,'Bundled Gross Monthly 4 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',125,'Bundled Gross Monthly 5 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',126,'Bundled Gross Monthly 6 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',127,'Bundled Gross Monthly 7 delay','G');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',131,'Pass Thru Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',132,'Pass Thru Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',133,'Pass Thru Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',134,'Pass Thru Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',135,'Pass Thru Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',136,'Pass Thru Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',137,'Pass Thru Net Daily 7 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',141,'Bundled Net Daily 1 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',142,'Bundled Net Daily 2 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',143,'Bundled Net Daily 3 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',144,'Bundled Net Daily 4 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',145,'Bundled Net Daily 5 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',146,'Bundled Net Daily 6 delay','N');
Insert into SETTL_PLAN (INSTITUTION_ID,SETTL_PLAN_ID,PLAN_DESC,SETTL_PLAN_TYPE) values ('134',147,'Bundled Net Daily 7 delay','N');
