REM INSERTING into ACCT_POSTING_PLAN
SET DEFINE OFF;


INSERT INTO "MASCLR"."SETTL_PLAN_TID" (INSTITUTION_ID, SETTL_PLAN_ID, TID, CURR_CODE, CARD_SCHEME, SETTL_FLAG, GL_ACCT_DEBIT, GL_ACCT_CREDIT, DELAY_FACTOR0, DELAY_FACTOR1, DELAY_FACTOR2, DELAY_FACTOR3, DELAY_FACTOR4, DELAY_FACTOR5, DELAY_FACTOR6, SETTL_FREQ, SETTL_DATE_LIST_ID, NEXT_SETTL_DATE, PAYMENT_TERM, DAY_OF_MONTH, HOL_DELAY_FACTOR) VALUES ('107', '1', '010004130002', '840', '00', 'Y', 'FEE-ACCUM-IN', 'ISO-COUNT-FEE', '0', '0', '0', '0', '0', '0', '0', 'M', '0', TO_DATE('30-SEP-13', 'DD-MON-YY'), '0', '31', '0');


