REM Add template mas_code_grp values

REM $Id: 0_6_template_mas_code_grp.sql 17 2016-10-25 15:22:05Z bjones $


REM INSERTING into MAS_CODE_GRP
SET DEFINE OFF;
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14, 'AMEX_JP_BASE_TIER1', 'AMEX_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14,  'DBT_JP_BASE_TIER1',  'DBT_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14, 'DISC_JP_BASE_TIER1', 'DISC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14,   'MC_JP_BASE_TIER1',   'MC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14, 'VISA_JP_BASE_TIER1', 'VISA_DISCOUNT');

INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14, 'AMEX_JP_BASE_TIER2', 'AMEX_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14,  'DBT_JP_BASE_TIER2',  'DBT_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14, 'DISC_JP_BASE_TIER2', 'DISC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14,   'MC_JP_BASE_TIER2',   'MC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14, 'VISA_JP_BASE_TIER2', 'VISA_DISCOUNT');

INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14, 'AMEX_JP_BASE_TIER3', 'AMEX_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14,  'DBT_JP_BASE_TIER3',  'DBT_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14, 'DISC_JP_BASE_TIER3', 'DISC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14,   'MC_JP_BASE_TIER3',   'MC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107', 14, 'VISA_JP_BASE_TIER3', 'VISA_DISCOUNT');


INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9, 'AMEX_JP_BASE_TIER1', 'AMEX_T1');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9,  'DBT_JP_BASE_TIER1',  'DBT_T1');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9, 'DISC_JP_BASE_TIER1', 'DISC_T1');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9,   'MC_JP_BASE_TIER1',   'MC_T1');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9, 'VISA_JP_BASE_TIER1', 'VISA_T1');

INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9, 'AMEX_JP_BASE_TIER2', 'AMEX_T2');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9,  'DBT_JP_BASE_TIER2',  'DBT_T2');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9, 'DISC_JP_BASE_TIER2', 'DISC_T2');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9,   'MC_JP_BASE_TIER2',   'MC_T2');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9, 'VISA_JP_BASE_TIER2', 'VISA_T2');

INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9, 'AMEX_JP_BASE_TIER3', 'AMEX_T3');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9,  'DBT_JP_BASE_TIER3',  'DBT_T3');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9, 'DISC_JP_BASE_TIER3', 'DISC_T3');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9,   'MC_JP_BASE_TIER3',   'MC_T3');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('107',  9, 'VISA_JP_BASE_TIER3', 'VISA_T3');




REM INSERTING into MAS_CODE_GRP
SET DEFINE OFF;
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14, 'AMEX_JP_BASE_TIER1', 'AMEX_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14,  'DBT_JP_BASE_TIER1',  'DBT_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14, 'DISC_JP_BASE_TIER1', 'DISC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14,   'MC_JP_BASE_TIER1',   'MC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14, 'VISA_JP_BASE_TIER1', 'VISA_DISCOUNT');

INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14, 'AMEX_JP_BASE_TIER2', 'AMEX_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14,  'DBT_JP_BASE_TIER2',  'DBT_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14, 'DISC_JP_BASE_TIER2', 'DISC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14,   'MC_JP_BASE_TIER2',   'MC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14, 'VISA_JP_BASE_TIER2', 'VISA_DISCOUNT');

INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14, 'AMEX_JP_BASE_TIER3', 'AMEX_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14,  'DBT_JP_BASE_TIER3',  'DBT_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14, 'DISC_JP_BASE_TIER3', 'DISC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14,   'MC_JP_BASE_TIER3',   'MC_DISCOUNT');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129', 14, 'VISA_JP_BASE_TIER3', 'VISA_DISCOUNT');


INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9, 'AMEX_JP_BASE_TIER1', 'AMEX_T1');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9,  'DBT_JP_BASE_TIER1',  'DBT_T1');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9, 'DISC_JP_BASE_TIER1', 'DISC_T1');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9,   'MC_JP_BASE_TIER1',   'MC_T1');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9, 'VISA_JP_BASE_TIER1', 'VISA_T1');

INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9, 'AMEX_JP_BASE_TIER2', 'AMEX_T2');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9,  'DBT_JP_BASE_TIER2',  'DBT_T2');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9, 'DISC_JP_BASE_TIER2', 'DISC_T2');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9,   'MC_JP_BASE_TIER2',   'MC_T2');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9, 'VISA_JP_BASE_TIER2', 'VISA_T2');

INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9, 'AMEX_JP_BASE_TIER3', 'AMEX_T3');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9,  'DBT_JP_BASE_TIER3',  'DBT_T3');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9, 'DISC_JP_BASE_TIER3', 'DISC_T3');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9,   'MC_JP_BASE_TIER3',   'MC_T3');
INSERT INTO MAS_CODE_GRP (INSTITUTION_ID, MAS_CODE_GRP_ID, QUALIFY_MAS_CODE, MAS_CODE) VALUES ('129',  9, 'VISA_JP_BASE_TIER3', 'VISA_T3');


REM INSERTING into FEE_PKG_MAS_CODE
SET DEFINE OFF;
Insert into FEE_PKG_MAS_CODE (INSTITUTION_ID, FEE_PKG_ID, MAS_CODE, CARD_SCHEME) values ('107', 33, 'DBT_JP_BASE_TIER2', '02');
Insert into FEE_PKG_MAS_CODE (INSTITUTION_ID, FEE_PKG_ID, MAS_CODE, CARD_SCHEME) values ('107', 34, 'DBT_JP_BASE_TIER2', '02');

Insert into FEE_PKG_MAS_CODE (INSTITUTION_ID, FEE_PKG_ID, MAS_CODE, CARD_SCHEME) values ('107', 33, 'DBT_JP_BASE_TIER3', '02');
Insert into FEE_PKG_MAS_CODE (INSTITUTION_ID, FEE_PKG_ID, MAS_CODE, CARD_SCHEME) values ('107', 34, 'DBT_JP_BASE_TIER3', '02');

REM INSERTING into FEE_PKG_MAS_CODE
SET DEFINE OFF;
Insert into FEE_PKG_MAS_CODE (INSTITUTION_ID, FEE_PKG_ID, MAS_CODE, CARD_SCHEME) values ('129', 33, 'DBT_JP_BASE_TIER2', '02');
Insert into FEE_PKG_MAS_CODE (INSTITUTION_ID, FEE_PKG_ID, MAS_CODE, CARD_SCHEME) values ('129', 33, 'DBT_JP_BASE_TIER3', '02');
commit;
