REM

REM $Id: 4_0_add_mas_code_n_mas_fees.sql 8 2016-10-18 15:38:11Z bjones $


select * from flmgr_interchange_rates
where card_scheme != '02'
and usage in ('ACTIVITY_ADMIN', 'INFRASTRUCT_SECURITY', 'NETWORK', 'PRE_AUTH', 'VISA_SWITCH', 'SWITCH_COMPLETION')
;


/*
USAGE                CARD_SCHEME
-------------------- -----------
ACTIVITY_ADMIN       02
ACTIVITY_ADMIN       03          d
ACTIVITY_ADMIN       04          d
ACTIVITY_ADMIN       05          d
ACTIVITY_ADMIN       08          d
CHECK_CARD_DISCOUNT  03
CHECK_CARD_DISCOUNT  04
CHECK_CARD_DISCOUNT  05
CHECK_CARD_DISCOUNT  08
DEFAULT_DISCOUNT     02
DEFAULT_DISCOUNT     03
DEFAULT_DISCOUNT     04
DEFAULT_DISCOUNT     05
DEFAULT_DISCOUNT     08
INFRASTRUCT_SECURITY 02
INFRASTRUCT_SECURITY 03          d
INFRASTRUCT_SECURITY 04          d
INFRASTRUCT_SECURITY 05          d
INFRASTRUCT_SECURITY 08          d
INTERCHANGE          03
INTERCHANGE          04
INTERCHANGE          05
INTERCHANGE          08
JP_MOBILE_DISCOUNT   03
JP_MOBILE_DISCOUNT   04
JP_MOBILE_DISCOUNT   05
JP_MOBILE_DISCOUNT   08
NETSECURE_DISCOUNT   03
NETSECURE_DISCOUNT   04
NETSECURE_DISCOUNT   05
NETSECURE_DISCOUNT   08
NETWORK              02
NETWORK              03          d
NETWORK              04          d
NETWORK              05          d
NETWORK              08          d
PRE_AUTH             02
PRE_AUTH             03          d
PRE_AUTH             04          d
PRE_AUTH             05          d
PRE_AUTH             08          d
REVTRAK_DISCOUNT     03
REVTRAK_DISCOUNT     04
REVTRAK_DISCOUNT     05
REVTRAK_DISCOUNT     08
SWITCH_COMPLETION    02
SWITCH_COMPLETION    03          d
SWITCH_COMPLETION    04          d
SWITCH_COMPLETION    05          d
SWITCH_COMPLETION    08          d
TFOCUSPAY_DISCOUNT   03
TFOCUSPAY_DISCOUNT   04
TFOCUSPAY_DISCOUNT   05
TFOCUSPAY_DISCOUNT   08
VISA_SWITCH          02
VISA_SWITCH          03          d
VISA_SWITCH          04          d
VISA_SWITCH          05          d
VISA_SWITCH          08          d

 59 rows selected

*/
