name: PEP8

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
jobs:
  PEP:
    runs-on: ubuntu-latest
    steps:
#     - name: Python Style Checker
#     - uses: andymckay/pycodestyle-action@0.1.3
    - uses: actions/checkout@master
    - name: Setup Python 3.9
      uses: actions/setup-python@master
      with:
        version: 3.9
    - name: flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=120 --statistics
